import { expect, test } from '@playwright/test'

test.describe.serial('Stages 1–4 browser journey', () => {
  test('ClientWorks navigation preserves client and search context', async ({ page }) => {
    const errors: string[] = []
    page.on('pageerror', error => errors.push(error.message))
    await page.goto('/home')
    await expect(page.getByRole('heading', { name: 'Welcome back, Alex.' })).toBeVisible()
    await page.screenshot({ path: 'test-results/home.png', fullPage: true })
    await page.getByRole('link', { name: 'Clients', exact: true }).click()
    await page.getByRole('textbox', { name: 'Search clients' }).fill('Maya')
    await expect(page.getByText('Elena Ruiz', { exact: true })).not.toBeVisible()
    await page.getByRole('link', { name: 'MB Maya Bennett' }).click()
    await expect(page.getByRole('heading', { name: 'Maya Bennett', exact: true }).first()).toBeVisible()
    await page.getByRole('link', { name: 'View all accounts' }).click()
    await expect(page.getByRole('link', { name: 'Maya Bennett Individual', exact: true })).toBeVisible()
    await page.getByRole('link', { name: 'Maya Bennett Individual', exact: true }).click()
    await expect(page.getByText('18 Willow Lane, Portland, OR 97205', { exact: true })).toBeVisible()
    await page.getByRole('link', { name: 'Return to client profile' }).click()
    await page.getByRole('link', { name: 'Back to clients' }).click()
    await expect(page.getByRole('textbox', { name: 'Search clients' })).toHaveValue('Maya')
    await page.getByRole('link', { name: 'MB Maya Bennett' }).click()
    await page.getByRole('link', { name: 'Open LifeSync', exact: true }).click()
    await expect(page.getByRole('heading', { name: 'Confirm the life event' })).toBeVisible()
    await expect(page.getByLabel('Affected person')).toHaveValue('Maya Bennett')
    await expect(page.getByRole('button', { name: 'Confirm event', exact: true })).toBeDisabled()
    expect(errors).toEqual([])
  })

  test('Divorce review enforces intent and approval, then resumes after refresh', async ({ page, request }) => {
    const errors: string[] = []
    page.on('pageerror', error => errors.push(error.message))
    await page.goto('/lifesync/C001')
    await page.getByRole('checkbox', { name: 'I confirm this event as the assigned advisor.' }).check()
    await page.getByRole('button', { name: 'Confirm event', exact: true }).click()
    await page.getByRole('button', { name: 'Load fixture findings' }).click()
    const address = page.locator('.finding-card').filter({ has: page.getByRole('heading', { name: 'Mailing address needs review' }) })
    const beneficiary = page.locator('.finding-card').filter({ has: page.getByRole('heading', { name: 'Former spouse is still listed' }) })
    await expect(address).toBeVisible()
    await address.getByRole('button', { name: 'WB:N002:note' }).click()
    await expect(page.getByRole('dialog')).toBeVisible()
    await expect(page.getByText('Earlier address note — conflicting evidence', { exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'Close evidence' }).click()
    await beneficiary.getByRole('button', { name: 'Create follow-up' }).click()
    await beneficiary.getByLabel('Reason / requested follow-up').fill('Ask Maya for explicit beneficiary instructions. No replacement has been selected.')
    await beneficiary.getByLabel('Task owner').selectOption('support-01')
    await beneficiary.getByRole('button', { name: 'Save decision' }).click()
    await expect(page.getByText('Taylor Chen · Needs date · Simulated CRM task', { exact: true })).toBeVisible()
    await address.getByRole('button', { name: 'Mark evidence reviewed' }).click()
    await address.getByText('Record specific client instructions', { exact: true }).click()
    await address.getByLabel('Client-confirmed account address').fill('92 Harbor Street, Portland, OR 97209')
    await address.getByLabel('Instruction details / reason').fill('Maya explicitly confirmed this address during the synthetic recorded call.')
    await address.getByRole('checkbox', { name: 'The client explicitly confirmed this value' }).check()
    await address.getByRole('button', { name: 'Save confirmed instruction' }).click()
    await address.getByRole('button', { name: 'Prepare validated draft' }).click()
    await page.getByRole('button', { name: 'Drafts & approvals' }).click()
    await expect(page.getByRole('button', { name: 'Submit simulated request' })).toBeDisabled()
    await page.getByRole('button', { name: 'Approve exact draft version' }).click()
    await page.getByRole('checkbox', { name: 'Client instruction record' }).check()
    await expect(page.getByRole('button', { name: 'Submit simulated request' })).toBeDisabled()
    await page.getByRole('checkbox', { name: 'Maya Bennett Simulated signature only' }).check()
    await expect(page.getByRole('button', { name: 'Submit simulated request' })).toBeEnabled()
    await page.screenshot({ path: 'test-results/lifesync.png', fullPage: true })
    await page.getByRole('button', { name: 'Submit simulated request' }).click()
    await page.getByRole('button', { name: 'Retry same submission' }).click()
    await page.getByRole('button', { name: 'Requests', exact: true }).click()
    await page.getByRole('button', { name: 'Simulate processing' }).click()
    await page.getByRole('button', { name: 'Simulate completion' }).click()
    await expect(page.getByText('Simulated completion receipt', { exact: true })).toBeVisible()
    await page.reload()
    await expect(page.getByText('Simulated completion receipt', { exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'Review', exact: true }).click()
    await expect(beneficiary.getByText('Needs information', { exact: true })).toBeVisible()
    await expect(page.locator('.lifecycle-client').getByText('Open', { exact: true })).toBeVisible()
    const savedRequests = await request.get('/api/requests')
    expect((await savedRequests.json()).length).toBe(1)
    const unauthorized = await request.get('/api/clients/C002')
    expect(unauthorized.status()).toBe(403)
    expect(errors).toEqual([])
  })

  test('Wealthbox shows explicit mappings, visible conflicts, and two-way sync', async ({ page }) => {
    await page.goto('/wealthbox/contacts/W004?tab=lpl')
    await expect(page.getByRole('heading', { name: 'Unlinked', exact: true })).toBeVisible()
    await page.goto('/wealthbox/contacts/W001')
    await expect(page.getByText('Earlier address note — conflicting evidence', { exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'LPL Financial', exact: true }).click()
    await expect(page.getByRole('columnheader', { name: 'Account', exact: true })).toBeVisible()
    await expect(page.getByRole('link', { name: 'Open in LPL Financial' })).toHaveAttribute('href', '/clients/C001')
    await page.getByLabel('Client-confirmed contact value').fill('92 Harbor Street, Portland, OR 97209')
    await page.getByLabel('Instruction source / confirmation record').fill('Maya confirmed the synthetic contact update on the recorded call.')
    await page.getByRole('checkbox', { name: 'I reviewed and approve' }).check()
    await page.getByRole('button', { name: 'Demonstrate version conflict' }).click()
    await expect(page.getByText('Contact update needs review', { exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'Synchronize approved contact field' }).click()
    await expect(page.getByText('ClientWorks v2 ↔ Wealthbox v2', { exact: true })).toBeVisible()
    await page.getByLabel('Update originates in').selectOption('wealthbox')
    await page.getByLabel('Supported field').selectOption('primary_email')
    await page.getByLabel('Client-confirmed contact value').fill('maya.updated@example.test')
    await page.getByLabel('Instruction source / confirmation record').fill('Maya explicitly confirmed her synthetic primary email address.')
    await page.getByRole('checkbox', { name: 'I reviewed and approve' }).check()
    await page.getByRole('button', { name: 'Synchronize approved contact field' }).click()
    await expect(page.getByText('ClientWorks v3 ↔ Wealthbox v3', { exact: true })).toBeVisible()
    await page.screenshot({ path: 'test-results/wealthbox.png', fullPage: true })
  })

  test('Mobile layouts remain usable without page overflow', async ({ page }) => {
    await page.setViewportSize({ width: 390, height: 844 })
    for (const path of ['/home', '/clients', '/accounts', '/lifesync/C001', '/wealthbox/contacts/W001?tab=lpl']) {
      await page.goto(path)
      await expect(page.getByRole('heading', { level: 1 })).toBeVisible()
      await expect(page.getByRole('status').filter({ hasText: 'Loading workspace' })).toHaveCount(0)
      const overflow = await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth)
      expect(overflow, path).toBe(false)
    }
    await page.goto('/lifesync/C001')
    await expect(page.getByRole('heading', { name: 'Former spouse is still listed' })).toBeVisible()
    await page.screenshot({ path: 'test-results/mobile.png', fullPage: true })
  })
})
