import { useEffect, useState, type FormEvent } from 'react'
import { Activity, ArrowRight, ArrowUpRight, Check, CheckCircle2, ChevronRight, Clock3, FileCheck2, FileText, History, Info, Link2, LockKeyhole, MapPin, ShieldCheck, Users } from 'lucide-react'
import { Link, useParams, useSearchParams } from 'react-router-dom'
import { api, useAction, useResource } from './api'
import { rememberClient } from './App'
import { AsyncCheckbox, Button, date, Empty, EvidenceModal, LoadError, Loading, Notice, owners, PageTitle, Panel, SourceMeta, Status, TaskList } from './ui'
import type { Beneficiary, Case, Context, Draft, Finding, Request } from './types'

type Action = ReturnType<typeof useAction>
type EvidenceOpener = (source: string) => void

export default function LifeSync() {
  const { clientId = 'C001' } = useParams()
  const ctx = useResource<Context>(`/clients/${clientId}/context`)
  const caseResource = useResource<Case | null>(`/clients/${clientId}/case`)
  const [params, setParams] = useSearchParams()
  const tab = params.get('tab') ?? 'review'
  const [sourceId, setSourceId] = useState<string | null>(null)
  const refresh = () => { caseResource.reload(); ctx.reload() }
  const action = useAction(refresh)
  useEffect(() => { if (ctx.data) rememberClient(clientId) }, [ctx.data, clientId])
  if (ctx.loading || caseResource.loading) return <Loading/>
  if (ctx.error || caseResource.error || !ctx.data) return <LoadError message={ctx.error || caseResource.error} retry={refresh}/>
  const context = ctx.data, caseData = caseResource.data
  const tabs = [['review', 'Review'], ['evidence', 'Evidence'], ['drafts', 'Drafts & approvals'], ['requests', 'Requests'], ['history', 'History']]
  return <>
    <div className="breadcrumbs"><Link to="/clients">Clients</Link><ChevronRight size={13}/><Link to={`/clients/${clientId}`}>{context.client.display_name}</Link><ChevronRight size={13}/><span>LifeSync</span></div>
    <PageTitle eyebrow="Connected lifecycle review" title="LifeSync" description="The right context. The client's intent. A clear path forward." action={<span className="fixture-label"><FileText size={15}/> Stage 4 · Fixture analysis</span>}/>
    <Notice error={action.error} success={action.success}/>
    <div className="lifecycle-client"><div className="client-avatar">{context.client.display_name.split(' ').map(word => word[0]).join('')}</div><div className="grow"><strong>{context.client.display_name}</strong><span>{clientId} · {context.accounts.length} accounts · {caseData ? `${caseData.event.event_type} review` : 'Event not yet confirmed'}</span></div>{caseData && <Status value={caseData.status}/>}<Link className="text-link" to={context.contact ? `/wealthbox/contacts/${context.contact.crm_contact_id}` : '/wealthbox'}><Link2 size={15}/>Linked Wealthbox context <ArrowUpRight size={14}/></Link></div>
    <div className="workflow-strip">{['Confirm event', 'Review evidence', 'Capture instructions', 'Approve & sign', 'Track outcomes'].map((label, index) => {
      const complete = !!caseData && (index === 0 || (index === 1 && caseData.findings.length > 0 && caseData.findings.every(finding => finding.reviewed || finding.status === 'No change')) || (index === 2 && caseData.findings.length > 0 && caseData.findings.every(finding => finding.instruction || finding.status === 'No change')) || (index === 3 && caseData.drafts.length > 0 && caseData.drafts.every(draft => draft.request)) || (index === 4 && caseData.status === 'Completed'))
      return <div className={`workflow-step ${complete ? 'complete' : ''}`} key={label}><span>{complete ? <Check size={13}/> : index + 1}</span>{label}</div>
    })}</div>
    <nav className="section-tabs" aria-label="LifeSync sections">{tabs.map(([value, label]) => <button key={value} className={tab === value ? 'active' : ''} onClick={() => setParams({ tab: value })}>{label}{value === 'drafts' && !!caseData?.drafts.length && <span>{caseData.drafts.length}</span>}</button>)}</nav>
    <div className="lifecycle-layout"><div className="lifecycle-content">
      {tab === 'review' && (!caseData ? <EventForm context={context} action={action}/> : <><EventSummary caseData={caseData}/>{!caseData.analyzed_at ? <Panel className="analysis-card"><div className="analysis-icon"><Activity size={27}/></div><h2>Bring the review into focus.</h2><p>Load the annotated, deterministic findings for this synthetic case. Each review item links to authorized source records.</p><div className="notice info"><Info size={17}/><span>This step uses a seeded fixture. No AI model is called.</span></div><Button className="primary" disabled={action.busy} onClick={() => action.run(`/cases/${caseData.case_id}/analyze-fixture`, 'POST', undefined, 'Fixture findings loaded. Review the cited evidence.')}>Load fixture findings <ArrowRight size={15}/></Button></Panel> : <><div className="review-heading"><h2>Items for your review <span className="count-pill">{caseData.findings.length}</span></h2><span className="muted small">{caseData.resolved_count} resolved · {caseData.unresolved_count} open</span></div>{caseData.findings.map(finding => <FindingCard key={finding.finding_id} finding={finding} caseData={caseData} context={context} action={action} openEvidence={setSourceId}/>)}<Panel title="Follow-ups"><TaskList tasks={caseData.tasks}/></Panel></>}</>)}
      {tab === 'evidence' && <EvidenceView context={context} caseData={caseData ?? null} openEvidence={setSourceId}/>}
      {tab === 'drafts' && (caseData?.drafts.length ? caseData.drafts.map(draft => <DraftCard key={draft.draft_id} draft={draft} context={context} action={action} openEvidence={setSourceId}/>) : <Panel><Empty title="A draft starts with specific instructions">Review the finding, confirm the client's requested value, and prepare the request.</Empty><Button onClick={() => setParams({ tab: 'review' })}>Return to review</Button></Panel>)}
      {tab === 'requests' && <RequestTracking clientId={clientId} action={action}/>}
      {tab === 'history' && <Panel title="Audit history" eyebrow="Recorded decisions & outcomes">{caseData?.audit.length ? <div className="audit-list">{[...caseData.audit].reverse().map(entry => <div className="audit-entry" key={entry.audit_id}><div className="audit-dot"><History size={14}/></div><div><strong>{entry.action.replaceAll('_', ' ')}</strong><p>{entry.outcome}</p><small>{owners[entry.actor] ?? entry.actor} · {new Date(entry.timestamp).toLocaleString()}</small><details><summary>Recorded versions & details</summary><pre className="record-json">{JSON.stringify(entry.details, null, 2)}</pre></details></div></div>)}</div> : <Empty title="No case history yet">Confirm an event to begin the audit trail.</Empty>}</Panel>}
    </div><aside className="lifecycle-aside"><Panel title="Case at a glance"><dl className="compact-details"><div><dt>Case owner</dt><dd>{owners[caseData?.owner ?? 'advisor-01']}</dd></div><div><dt>Event</dt><dd>{caseData?.event.event_type ?? 'Needs confirmation'}</dd></div><div><dt>Open items</dt><dd>{caseData?.unresolved_count ?? '—'}</dd></div><div><dt>Analysis</dt><dd>Seeded fixture</dd></div><div><dt>CRM link</dt><dd><Status value={context.contact ? 'Linked' : 'Unlinked'}/></dd></div></dl>{caseData && <div className="case-progress"><div><span>Review progress</span><strong>{caseData.resolved_count}/{caseData.findings.length}</strong></div><progress max={caseData.findings.length || 1} value={caseData.resolved_count}/></div>}</Panel><div className="safety-card"><ShieldCheck size={22}/><h3>You stay in control.</h3><p>Findings propose review. You confirm the event, the instructions, and the exact draft version.</p><div className="safety-divider"/><p>Contact sync and account servicing have separate outcomes.</p></div><Panel title="Source coverage"><div className="coverage-list">{Object.entries(context.coverage).map(([label, status]) => <div key={label}><span>{label.replaceAll('_', ' ')}</span><Status value={status}/></div>)}</div>{context.errors.map(error => <p className="small warning-text" key={error}>{error}</p>)}</Panel></aside></div>
    {sourceId && <EvidenceModal sourceId={sourceId} onClose={() => setSourceId(null)}/>}
  </>
}

function EventForm({ context, action }: { context: Context; action: Action }) {
  const [eventType, setEventType] = useState(context.client.event_hint)
  const [person, setPerson] = useState(context.client.event_hint === 'Death' ? 'Luis Ruiz' : context.client.display_name)
  const [role, setRole] = useState(context.client.event_hint === 'Death' ? 'beneficiary' : 'client')
  const [eventDate, setEventDate] = useState('')
  const [owner, setOwner] = useState('advisor-01')
  const [confirmed, setConfirmed] = useState(false)
  const [refs, setRefs] = useState<string[]>(context.notes.length ? [context.notes[0].source_id] : [context.client.source_id])
  function submit(event: FormEvent) {
    event.preventDefault()
    action.run(`/clients/${context.client.client_id}/case`, 'POST', { event_type: eventType, affected_person: person, affected_role: role, event_date: eventDate || null, evidence_refs: refs, owner, confirmed }, 'Event confirmed and saved. Load fixture findings to continue.')
  }
  return <Panel title="Confirm the life event" eyebrow="Start with what the client has told you"><p className="muted">Confirm the event and affected person before beginning the review. The event date can remain unknown.</p><form onSubmit={submit} className="form-stack"><div className="form-grid"><label>Event type<select value={eventType} onChange={event => setEventType(event.target.value)}>{['Divorce', 'Marriage', 'Death'].map(value => <option key={value}>{value}</option>)}</select></label><label>Affected person<input required value={person} onChange={event => setPerson(event.target.value)}/></label><label>Affected role<select value={role} onChange={event => setRole(event.target.value)}>{[['client', 'Client'], ['account_owner', 'Account owner'], ['beneficiary', 'Beneficiary'], ['spouse', 'Spouse']].map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label><label>Event date, if known<input type="date" value={eventDate} onChange={event => setEventDate(event.target.value)}/></label><label>Case owner<select value={owner} onChange={event => setOwner(event.target.value)}>{Object.entries(owners).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label></div><fieldset className="evidence-checks"><legend>Supporting evidence</legend>{[...context.notes, ...context.documents, context.client].map(record => <label className="checkbox-row" key={record.source_id}><input type="checkbox" checked={refs.includes(record.source_id)} onChange={event => setRefs(current => event.target.checked ? [...current, record.source_id] : current.filter(ref => ref !== record.source_id))}/><span>{'title' in record ? record.title : 'ClientWorks contact record'}<small>{record.source_id} · v{record.version}</small></span></label>)}</fieldset>{eventType === 'Death' && <div className="notice warning"><Info size={18}/><span>Identify whose death is being reviewed. An account-owner death and a beneficiary death require different authority checks.</span></div>}<label className="checkbox-row confirmation"><input type="checkbox" checked={confirmed} onChange={event => setConfirmed(event.target.checked)}/><span>I confirm this event as the assigned advisor.</span></label><Button className="primary" disabled={action.busy || !confirmed || !refs.length} type="submit">Confirm event <ArrowRight size={15}/></Button></form></Panel>
}

function EventSummary({ caseData }: { caseData: Case }) {
  return <div className="event-summary"><CheckCircle2 size={21}/><div><strong>{caseData.event.event_type} confirmed</strong><p>{caseData.event.affected_person} · {caseData.event.affected_role.replaceAll('_', ' ')} · Event date: {caseData.event.event_date ? date(caseData.event.event_date) : 'Unknown'}</p><small>Confirmed by {owners[caseData.confirmed_by] ?? caseData.confirmed_by} · {date(caseData.confirmed_at)}</small></div><span className="event-tag">Saved case</span></div>
}

function FindingCard({ finding, caseData, context, action, openEvidence }: { finding: Finding; caseData: Case; context: Context; action: Action; openEvidence: EvidenceOpener }) {
  const [decision, setDecision] = useState('')
  const [reason, setReason] = useState('')
  const [owner, setOwner] = useState('advisor-01')
  const [due, setDue] = useState('')
  const base = `/cases/${caseData.case_id}/findings/${finding.finding_id}`
  const locked = ['Submitted', 'Processing', 'Completed'].includes(finding.status)
  function saveDecision(event: FormEvent) {
    event.preventDefault()
    action.run(base, 'PATCH', { expected_version: finding.version, disposition: decision, reason, task_owner: owner, due_date: due || null }, decision === 'no_change' ? 'No-change decision recorded.' : 'Owned follow-up saved.')
  }
  return <Panel className="finding-card"><div className="finding-heading"><div className={`finding-icon ${finding.field === 'address' ? 'teal' : 'plum'}`}>{finding.field === 'address' ? <MapPin size={21}/> : <Users size={21}/>}</div><div className="grow"><div className="eyebrow">{finding.account_id ?? 'Case review'} · Fixture finding</div><h3>{finding.title}</h3></div><Status value={finding.status}/></div><p className="finding-reason">{finding.reason}</p><div className="source-buttons">{finding.evidence_refs.map(ref => <button key={ref} className="source-button" onClick={() => openEvidence(ref)}><FileText size={13}/>{ref}<ArrowUpRight size={12}/></button>)}</div>{finding.conflicting_evidence && <div className="conflict-note"><Info size={16}/><span>Two dated notes give different addresses. Review both; a client-confirmed instruction is required.</span></div>}{finding.decision && <div className="decision-record"><Check size={14}/><span>{finding.decision.reason}</span></div>}
    {!locked && finding.status !== 'No change' && <><div className="finding-actions">{!finding.reviewed ? <Button disabled={action.busy} onClick={() => action.run(base, 'PATCH', { expected_version: finding.version, disposition: 'reviewed', reason: 'Advisor reviewed the cited evidence and any conflicting dated records.', task_owner: 'advisor-01', due_date: null }, 'Evidence marked reviewed. Confirm specific client instructions.')}>Mark evidence reviewed</Button> : <span className="reviewed-label"><CheckCircle2 size={15}/>Evidence reviewed</span>}<Button className="quiet" disabled={action.busy} onClick={() => { setDecision('needs_information'); setReason('') }}>Create follow-up</Button><Button className="quiet" disabled={action.busy} onClick={() => { setDecision('no_change'); setReason('') }}>Record no change</Button><Button className="quiet" disabled={action.busy} onClick={() => { setDecision('manual_review'); setReason('') }}>Manual review</Button></div>{decision && <form className="sub-form" onSubmit={saveDecision}><h4>{decision === 'no_change' ? 'Document the no-change decision' : 'Assign the next step'}</h4><label>Reason / requested follow-up<textarea required minLength={8} value={reason} onChange={event => setReason(event.target.value)} placeholder="Record the specific reason or missing information…"/></label>{decision !== 'no_change' && <div className="form-grid"><label>Task owner<select value={owner} onChange={event => setOwner(event.target.value)}>{Object.entries(owners).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label><label>Due date (blank = Needs date)<input type="date" value={due} onChange={event => setDue(event.target.value)}/></label></div>}<div className="button-row"><Button className="primary" type="submit" disabled={action.busy}>Save decision</Button><Button type="button" className="quiet" onClick={() => setDecision('')}>Cancel</Button></div></form>}
      {finding.reviewed && finding.field && <details className="instruction-details" open={!!finding.instruction}>
        <summary>{finding.instruction ? 'Confirmed client instruction' : 'Record specific client instructions'}</summary>
        <Button className="quiet spaced" disabled={action.busy} onClick={() => action.run(base, 'PATCH', {
          expected_version: finding.version, disposition: 'reviewed',
          reason: 'Advisor reviewed current source versions and retained any conflicting evidence for review.',
          task_owner: 'advisor-01', due_date: null,
        }, 'Current evidence reviewed. Reconfirm the client instruction before updating the draft.')}>Review current evidence again</Button>
        <InstructionForm finding={finding} context={context} action={action} endpoint={`${base}/instruction`} expectedVersion={finding.version}/>
        {finding.instruction && <div className="button-row">
          {!finding.draft_id && <Button className="primary" disabled={action.busy} onClick={() => action.run(`${base}/draft`, 'POST', { expected_version: finding.version }, 'Validated draft prepared. Open Drafts & approvals.')}>Prepare validated draft<FileCheck2 size={15}/></Button>}
          {finding.draft_id && <Link className="button primary" to="?tab=drafts">Open saved draft <ArrowRight size={14}/></Link>}
        </div>}
      </details>}
    </>}{locked && <div className="locked-note"><LockKeyhole size={14}/>Submitted records remain tracked; edits cannot roll back an institution request.</div>}{finding.status === 'No change' && <div className="finding-actions"><Button className="quiet" disabled={action.busy} onClick={() => action.run(base, 'PATCH', { expected_version: finding.version, disposition: 'needs_information', reason: 'Advisor reopened the documented decision for further client review.', task_owner: 'advisor-01', due_date: null }, 'Finding reopened with an owned follow-up.')}>Reopen for review</Button></div>}
  </Panel>
}

function InstructionForm({ finding, context, action, endpoint, expectedVersion, draft }: { finding: Finding; context: Context; action: Action; endpoint: string; expectedVersion: number; draft?: Draft }) {
  const initial = draft?.proposed_value ?? finding.instruction?.value
  const [address, setAddress] = useState(typeof initial === 'string' ? initial : '')
  const [name, setName] = useState(Array.isArray(initial) ? initial[0]?.name ?? '' : '')
  const [relationship, setRelationship] = useState(Array.isArray(initial) ? initial[0]?.relationship ?? '' : '')
  const [sourceRef, setSourceRef] = useState(finding.instruction?.source_ref ?? context.documents[0]?.source_id ?? finding.evidence_refs[0])
  const [confirmed, setConfirmed] = useState(false)
  const [reason, setReason] = useState('')
  function submit(event: FormEvent) {
    event.preventDefault()
    const value: string | Beneficiary[] = finding.field === 'address' ? address : [{ name, relationship, percentage: 100 }]
    action.run(endpoint, draft ? 'PUT' : 'POST', { expected_version: expectedVersion, value, source_ref: sourceRef, client_confirmed: confirmed, reason }, draft ? 'Draft edited. Approval, documents, and signatures were cleared for the new version.' : 'Specific client instructions recorded.')
  }
  return <form className="instruction-form" onSubmit={submit}>{finding.field === 'address' ? <label>Client-confirmed account address<input required minLength={10} value={address} onChange={event => setAddress(event.target.value)} placeholder="Enter the complete address confirmed by the client"/><small className="muted">The fixture instruction record contains 92 Harbor Street, Portland, OR 97209.</small></label> : <><div className="notice warning"><Info size={17}/><span>Leave instructions unknown until the client explicitly supplies a beneficiary. This form supports one named beneficiary at 100%; the API supports multiple beneficiaries.</span></div><div className="form-grid"><label>Client-selected beneficiary<input required minLength={2} value={name} onChange={event => setName(event.target.value)} placeholder="Explicitly supplied name"/></label><label>Relationship<input required minLength={2} value={relationship} onChange={event => setRelationship(event.target.value)} placeholder="Client-supplied relationship"/></label></div></>}<label>Instruction source<select value={sourceRef} onChange={event => setSourceRef(event.target.value)}>{context.sources.map(record => <option value={record.source_id} key={record.source_id}>{record.source_id} · v{record.version}</option>)}</select></label><label>Instruction details / reason<textarea required minLength={8} value={reason} onChange={event => setReason(event.target.value)} placeholder="Describe the instruction and how it was confirmed…"/></label><label className="checkbox-row"><input type="checkbox" checked={confirmed} onChange={event => setConfirmed(event.target.checked)}/><span>The client explicitly confirmed this value and requested this account update.</span></label><Button disabled={action.busy || !confirmed} type="submit">{draft ? 'Save edited draft version' : 'Save confirmed instruction'}</Button></form>
}

function EvidenceView({ context, caseData, openEvidence }: { context: Context; caseData: Case | null; openEvidence: EvidenceOpener }) {
  const titles = new Map([...context.notes, ...context.documents].map(record => [record.source_id, record.title]))
  return <><Panel title="Authorized evidence" eyebrow="Records used in this review"><p className="muted">Every record keeps its source ID, version, and freshness. Conflicting source notes remain intact.</p>{caseData && <div className="notice info"><FileText size={17}/><span>{caseData.analysis_label}</span></div>}<div className="evidence-list">{context.sources.map(record => <button className="evidence-row" key={record.source_id} onClick={() => openEvidence(record.source_id)}><span className="evidence-icon"><FileText size={18}/></span><div className="grow"><strong>{titles.get(record.source_id) ?? record.source_id}</strong><SourceMeta record={record}/></div><ArrowUpRight size={16}/></button>)}</div></Panel><Panel title="Source coverage">{Object.entries(context.coverage).map(([key, value]) => <div className="coverage-row" key={key}><span>{key.replaceAll('_', ' ')}</span><Status value={value}/></div>)}{context.errors.map(error => <Notice key={error} error={error}/>)}</Panel></>
}

function Value({ value }: { value: string | Beneficiary[] }) { return typeof value === 'string' ? <p>{value}</p> : <div>{value.length ? value.map(person => <p key={person.name}>{person.name}<small>{person.relationship} · {person.percentage}%</small></p>) : <p className="muted">No entries</p>}</div> }

function DraftCard({ draft, context, action, openEvidence }: { draft: Draft; context: Context; action: Action; openEvidence: EvidenceOpener }) {
  const finding: Finding = { finding_id: draft.finding_id, field: draft.field, instruction: null } as Finding
  const [edit, setEdit] = useState(false)
  const locked = !!draft.request && draft.request.status !== 'Rejected'
  const submitKey = `${draft.draft_id}:v${draft.version}:submit`
  return <Panel className="draft-card"><div className="finding-heading"><div className="finding-icon teal"><FileCheck2 size={21}/></div><div className="grow"><div className="eyebrow">{draft.account_id} · Draft v{draft.version}</div><h3>{draft.field === 'address' ? 'Account address update' : 'Beneficiary designation update'}</h3></div><Status value={draft.status}/></div><div className="draft-compare"><div><span className="eyebrow">Current account value</span><Value value={draft.current_value}/></div><ArrowRight size={20}/><div className="proposed"><span className="eyebrow">Client-confirmed proposal</span><Value value={draft.proposed_value}/></div></div><div className="instruction-source"><span>Instruction evidence</span><button className="source-button" onClick={() => openEvidence(draft.instruction_source)}><FileText size={13}/>{draft.instruction_source}<ArrowUpRight size={12}/></button></div><div className="sample-requirements"><div className="eyebrow">{draft.requirements.label}</div>{draft.requirements.forms.map(form => <p key={form}><FileText size={15}/>{form}</p>)}</div>
    {!locked && <><div className="gate-section"><h4><ShieldCheck size={16}/>Approval of draft v{draft.version}</h4>{draft.approval ? <div className="approved-record"><CheckCircle2 size={16}/>Approved by {owners[draft.approval.actor]} · {date(draft.approval.timestamp)} · v{draft.approval.draft_version}</div> : <Button className="primary" disabled={action.busy} onClick={() => action.run(`/drafts/${draft.draft_id}/approve`, 'POST', { expected_version: draft.version }, `Draft v${draft.version} approved. Complete its simulated requirements.`)}>Approve exact draft version</Button>}</div><div className="gate-section"><h4><FileText size={16}/>Required simulated documents</h4>{draft.requirements.documents.map(document => <label className="checkbox-row" key={document}><AsyncCheckbox checked={!!draft.documents[document]} disabled={action.busy} onSave={provided => action.run(`/drafts/${draft.draft_id}/documents`, 'POST', { expected_version: draft.version, document, provided }, 'Simulated document status saved.')}/><span>{document}<small>Simulate receipt for this draft version</small></span></label>)}</div><div className="gate-section"><h4><Users size={16}/>Required simulated signatures</h4>{draft.requirements.signers.map(signer => <label className="checkbox-row" key={signer}><AsyncCheckbox checked={!!draft.signatures[signer]} disabled={action.busy} onSave={signed => action.run(`/drafts/${draft.draft_id}/signatures`, 'POST', { expected_version: draft.version, signer, signed }, 'Simulated signature status saved.')}/><span>{signer}<small>Simulated signature only · draft v{draft.version}</small></span></label>)}</div>{draft.blocked_reasons.length > 0 && <div className="blocked-box"><LockKeyhole size={17}/><div><strong>Before this request can be submitted</strong><ul>{draft.blocked_reasons.map(reason => <li key={reason}>{reason}</li>)}</ul></div></div>}<Notice error={draft.submission_error ?? undefined}/><div className="button-row"><Button className="primary" disabled={action.busy || draft.blocked_reasons.length > 0} onClick={() => action.run(`/drafts/${draft.draft_id}/submit`, 'POST', { expected_version: draft.version, idempotency_key: submitKey }, 'Simulated account request submitted once. Open Requests to reconcile.')}>Submit simulated request <ArrowRight size={15}/></Button><Button className="quiet" disabled={action.busy} onClick={() => setEdit(!edit)}>{edit ? 'Cancel editing' : 'Edit draft'}</Button></div>{edit && <div className="sub-form"><h4>Edit with confirmed instructions</h4><p className="muted small">A saved edit creates a new version and invalidates prior approval and signatures. Stale evidence must be reviewed again first.</p><InstructionForm draft={draft} finding={finding} context={context} action={action} endpoint={`/drafts/${draft.draft_id}`} expectedVersion={draft.version}/></div>}</>}
    {locked && <div className="submitted-footer"><Status value={draft.request!.status}/><Link className="text-link" to="?tab=requests">Track simulated request <ArrowRight size={14}/></Link><Button className="quiet" disabled={action.busy} onClick={() => action.run(`/drafts/${draft.draft_id}/submit`, 'POST', { expected_version: draft.version, idempotency_key: submitKey }, 'Retry returned the same logical request.')}>Retry same submission</Button></div>}
    <details className="draft-source-details"><summary>Source versions bound to this draft</summary>{Object.entries(draft.source_versions).map(([ref, version]) => <button className="source-button" key={ref} onClick={() => openEvidence(ref)}>{ref} · v{version}</button>)}</details>
  </Panel>
}

function RequestTracking({ clientId, action }: { clientId: string; action: Action }) {
  const requests = useResource<Request[]>('/requests')
  const [localError, setLocalError] = useState('')
  async function advance(request: Request, outcome: string) {
    setLocalError('')
    try {
      await api(`/requests/${request.request_id}/advance`, 'POST', { expected_version: request.version, outcome, reason: outcome === 'Rejected' ? 'Simulated institution rejected the request; advisor correction is required.' : 'Simulated institution processed the approved account update.' })
      requests.reload()
      await action.run(`/requests/${request.request_id}`, 'GET', undefined, `Simulated request ${outcome.toLowerCase()}.`)
    } catch (failure) { setLocalError(failure instanceof Error ? failure.message : 'Unable to update request.') }
  }
  function downloadReceipt(request: Request) {
    const url = URL.createObjectURL(new Blob([JSON.stringify(request.receipt, null, 2)], { type: 'application/json' }))
    const anchor = document.createElement('a'); anchor.href = url; anchor.download = `${request.external_request_id}-receipt.json`; anchor.click(); URL.revokeObjectURL(url)
  }
  const filtered = (requests.data ?? []).filter(request => request.client_id === clientId)
  return <Panel title="Request tracking" eyebrow="Account servicing outcomes"><p className="muted">These are simulated institution responses. Contact synchronization is tracked separately.</p><Notice error={localError}/>{requests.loading ? <Loading/> : requests.error ? <LoadError message={requests.error} retry={requests.reload}/> : !filtered.length ? <Empty title="No account requests submitted">Complete the approval, document, and signature gates on a draft.</Empty> : <div className="request-list">{filtered.map(request => <div className="request-card" key={request.request_id}><div className="finding-heading"><div className="finding-icon"><Clock3 size={20}/></div><div className="grow"><strong>{request.external_request_id}</strong><small>{request.account_id} · Draft v{request.draft_version}</small></div><Status value={request.status}/></div><SourceMeta record={request}/>{request.outcome_reason && <p className="muted small">{request.outcome_reason}</p>}{['Submitted', 'Processing'].includes(request.status) && <div className="button-row"><Button disabled={action.busy} onClick={() => advance(request, request.status === 'Submitted' ? 'Processing' : 'Completed')}>{request.status === 'Submitted' ? 'Simulate processing' : 'Simulate completion'}</Button><Button className="quiet danger" disabled={action.busy} onClick={() => advance(request, 'Rejected')}>Simulate rejection</Button></div>}{request.status === 'Rejected' && <Link className="text-link" to="?tab=review">Return to review and correct instructions <ArrowRight size={14}/></Link>}{request.receipt && <div className="receipt-card"><CheckCircle2 size={21}/><div className="grow"><strong>Simulated completion receipt</strong><p>{request.receipt.message}</p><small>{request.receipt.receipt_id} · {request.receipt.masked_account} · Account v{request.receipt.account_version}</small></div><Button className="quiet" onClick={() => downloadReceipt(request)}>Download receipt</Button></div>}</div>)}</div>}</Panel>
}
