import { useState, type FormEvent } from 'react'
import { ArrowUpRight, CheckCircle2, ChevronRight, ContactRound, ExternalLink, FileText, Link2, ListTodo, RefreshCw, Search, Settings2, Unlink, Users } from 'lucide-react'
import { Link, useParams, useSearchParams } from 'react-router-dom'
import { key, useAction, useResource } from './api'
import { Button, date, Empty, EvidenceModal, LoadError, Loading, money, Notice, PageTitle, Panel, SourceMeta, Status, TaskList } from './ui'
import type { Client, Contact, Sync } from './types'

export default function Wealthbox() {
  const { contactId } = useParams()
  const [params, setParams] = useSearchParams()
  const tab = params.get('tab') ?? 'activity', view = params.get('view') ?? 'contacts'
  const list = useResource<Contact[]>('/contacts')
  const contactResource = useResource<Contact>(`/contacts/${contactId ?? 'W001'}`)
  const clients = useResource<Client[]>('/clients')
  const [search, setSearch] = useState('')
  const [manage, setManage] = useState(false)
  const [selection, setSelection] = useState('')
  const [sourceId, setSourceId] = useState<string | null>(null)
  const action = useAction(() => { contactResource.reload(); list.reload() })
  const contact = contactId ? contactResource.data : null
  function saveLink(event: FormEvent) {
    event.preventDefault()
    if (contact) action.run(`/contacts/${contact.crm_contact_id}/link`, 'PUT', { expected_version: contact.version, client_id: selection || null, idempotency_key: key() }, 'Explicit client mapping saved.')
  }
  return <div className="crm-layout"><aside className="crm-sidebar"><Link className="wealthbox-brand" to="/wealthbox"><span className="wealthbox-symbol">w</span>wealthbox<span className="crm-label">CRM</span></Link><div className="crm-sidebar-label">WORKSPACE</div><Link className={view === 'contacts' ? 'selected' : ''} to="/wealthbox"><ContactRound size={18}/>Contacts</Link><Link className={view === 'tasks' ? 'selected' : ''} to="/wealthbox?view=tasks"><ListTodo size={18}/>Tasks</Link><Link className={view === 'notes' ? 'selected' : ''} to="/wealthbox?view=notes"><FileText size={18}/>Notes</Link><div className="crm-sidebar-label">INTEGRATIONS</div><Link className="lpl-launcher" to={contact?.client_id ? `/clients/${contact.client_id}` : '/clients'}><span>LPL</span>LPL Financial<ExternalLink size={13}/></Link><div className="crm-sidebar-footer"><CheckCircle2 size={17}/><p>Separate source records.<br/>Explicit client mappings.</p><small>Wealthbox simulation</small></div></aside><div className="crm-workspace"><div className="crm-topline"><span>Wealthbox CRM simulation</span><Link to="/home">Return to ClientWorks <ArrowUpRight size={14}/></Link></div><Notice error={action.error} success={action.success}/>
    {!contactId ? <><PageTitle eyebrow="Relationships & context" title={view === 'tasks' ? 'Tasks' : view === 'notes' ? 'Notes' : 'Contacts'} description="A familiar CRM view, connected to your advisor workspace."/>{list.loading ? <Loading/> : list.error ? <LoadError message={list.error} retry={list.reload}/> : view === 'tasks' ? <Panel title="Owned tasks"><TaskList tasks={(list.data ?? []).flatMap(item => item.tasks)}/></Panel> : view === 'notes' ? <Panel title="Dated relationship notes">{(list.data ?? []).flatMap(item => item.notes).map(note => <button className="evidence-row" key={note.note_id} onClick={() => setSourceId(note.source_id)}><FileText size={19}/><div className="grow"><strong>{note.title}</strong><small>{note.author} · {date(note.recorded_at)}</small></div><ArrowUpRight size={15}/></button>)}</Panel> : <Panel><div className="table-toolbar"><label className="search"><Search size={17}/><input aria-label="Search CRM contacts" placeholder="Search contacts" value={search} onChange={event => setSearch(event.target.value)}/></label><span className="filter-chip">My contacts</span></div><div className="table-wrap"><table><thead><tr><th>Contact</th><th>Email</th><th>Client link</th><th>Sync</th><th/></tr></thead><tbody>{list.data?.filter(item => item.display_name.toLowerCase().includes(search.toLowerCase())).map(item => <tr key={item.crm_contact_id}><td><Link className="client-cell" to={`/wealthbox/contacts/${item.crm_contact_id}`}><span className="client-avatar plum">{item.display_name.split(' ').map(word => word[0]).join('')}</span><strong>{item.display_name}</strong></Link></td><td>{item.primary_email}</td><td>{item.client_id ?? 'Unlinked'}</td><td><Status value={item.link_status}/></td><td><Link className="text-link" to={`/wealthbox/contacts/${item.crm_contact_id}`}>Open contact <ChevronRight size={14}/></Link></td></tr>)}</tbody></table></div></Panel>}</> : contactResource.loading ? <Loading/> : contactResource.error || !contact ? <LoadError message={contactResource.error} retry={contactResource.reload}/> : <><Link className="back-link" to="/wealthbox">← All contacts</Link><div className="crm-contact-heading"><div className="large-avatar plum">{contact.display_name.split(' ').map(word => word[0]).join('')}</div><div className="grow"><div className="eyebrow">Individual contact / {contact.crm_contact_id}</div><h1>{contact.display_name}</h1><p>{contact.primary_email} · {contact.phone}</p></div><Status value={contact.link_status}/></div><nav className="section-tabs" aria-label="Contact tabs"><button className={tab === 'activity' ? 'active' : ''} onClick={() => setParams({ tab: 'activity' })}>Activity</button><button disabled title="Email is unavailable; no messages are sent">Email</button><button className={tab === 'lpl' ? 'active' : ''} onClick={() => setParams({ tab: 'lpl' })}>LPL Financial</button></nav>
      {tab === 'activity' && <div className="crm-activity-grid"><div><Panel title="Dated notes" action={<span className="count-pill">{contact.notes.length}</span>}>{contact.notes.length ? contact.notes.map(note => <article className="crm-note" key={note.note_id}><div className="note-heading"><FileText size={17}/><strong>{note.title}</strong></div><div className="small muted">{note.author} · {date(note.recorded_at)}</div><p>{note.content}</p>{note.conflicting && <Status value="Conflicting evidence"/>}<SourceMeta record={note}/><Button className="quiet" onClick={() => setSourceId(note.source_id)}>Open source evidence <ArrowUpRight size={13}/></Button></article>) : <Empty title={contact.client_id ? 'No dated notes available' : 'Unlinked'}>No linked-client relationship notes are guessed.</Empty>}</Panel><Panel title="Owned tasks"><TaskList tasks={contact.tasks}/></Panel></div><Panel title="Contact details"><dl className="compact-details"><div><dt>Address</dt><dd>{contact.address}</dd></div><div><dt>Client mapping</dt><dd>{contact.client_id ?? 'Unlinked'}</dd></div><div><dt>Last synchronized</dt><dd>{contact.synced_at ? date(contact.synced_at) : 'Not synchronized'}</dd></div></dl><SourceMeta record={contact}/><Link className="button spaced" to="?tab=lpl">Open LPL Financial tab <ArrowRightIcon/></Link></Panel></div>}
      {tab === 'lpl' && <><Panel title="LPL Financial" eyebrow="Linked financial accounts" action={<div className="button-row"><Button disabled={action.busy} onClick={() => { setSelection(contact.client_id ?? ''); setManage(!manage) }}><Settings2 size={15}/>Manage Linked Clients</Button>{contact.client_id && <Link className="button primary" to={`/clients/${contact.client_id}`}>Open in LPL Financial <ExternalLink size={14}/></Link>}</div>}>{manage && <form className="link-manager" onSubmit={saveLink}><label>Explicit ClientWorks client mapping<select value={selection} onChange={event => setSelection(event.target.value)}><option value="">Unlinked</option>{clients.data?.map(client => <option key={client.client_id} value={client.client_id}>{client.display_name} ({client.client_id})</option>)}</select></label><Button type="submit" disabled={action.busy}>Save mapping</Button><Button type="button" className="quiet" onClick={() => setSelection('')}><Unlink size={14}/>Choose Unlinked</Button><p className="muted small">Existing mappings must be explicitly removed before relinking. No SSNs or name guesses are used.</p></form>}{contact.client_id ? <><div className="financial-total"><span>Total account value</span><strong>{money(contact.accounts.reduce((sum, account) => sum + account.value, 0))}</strong><small>{contact.accounts.length} accounts · Read-only ClientWorks projection</small></div><div className="table-wrap"><table><thead><tr>{['Account', 'Title', 'Type', 'Class', 'Value'].map(label => <th key={label}>{label}</th>)}</tr></thead><tbody>{contact.accounts.map(account => <tr key={account.account_id}><td><Link to={`/accounts/${account.account_id}`}>{account.masked_number}</Link><small>{account.account_id}</small></td><td>{account.title}</td><td>{account.type}</td><td>{account.class}</td><td className="number">{money(account.value)}</td></tr>)}</tbody></table></div><div className="table-footer">Financial accounts are projected for viewing. Beneficiaries and ownership do not synchronize as contacts.</div></> : <Empty title="Unlinked">Select an explicit client mapping to view financial accounts.</Empty>}</Panel>{contact.client_id && <SyncForm clientId={contact.client_id} onChanged={() => { contactResource.reload(); list.reload() }}/>}</>}
    </>}
    {sourceId && <EvidenceModal sourceId={sourceId} onClose={() => setSourceId(null)}/>}
  </div></div>
}

function ArrowRightIcon() { return <ChevronRight size={14}/> }

function SyncForm({ clientId, onChanged }: { clientId: string; onChanged: () => void }) {
  const resource = useResource<Sync>(`/clients/${clientId}/sync`)
  const action = useAction(() => { resource.reload(); onChanged() })
  const [origin, setOrigin] = useState('clientworks')
  const [field, setField] = useState('address')
  const [value, setValue] = useState('')
  const [instruction, setInstruction] = useState('')
  const [approved, setApproved] = useState(false)
  async function synchronize(conflict = false) {
    if (!resource.data?.contact) return
    const { client, contact } = resource.data
    const originVersion = origin === 'clientworks' ? client.version : contact.version
    const targetVersion = origin === 'clientworks' ? contact.version : client.version
    const saved = await action.run(`/clients/${clientId}/contact-sync`, 'POST', { origin, field, value, instruction_source: instruction, approved, expected_version: originVersion, target_version: conflict ? targetVersion + 1 : targetVersion, idempotency_key: key() }, 'Supported contact field propagated once. Account records were not changed.')
    if (!saved) resource.reload()
  }
  const unresolved = resource.data?.conflicts.filter(item => item.status === 'Needs review') ?? []
  return <Panel title="Supported contact synchronization" eyebrow="A separate demographic outcome"><Notice error={action.error} success={action.success}/>{resource.loading ? <Loading/> : resource.error || !resource.data ? <LoadError message={resource.error} retry={resource.reload}/> : <><div className="sync-boundary"><Link2 size={20}/><div><strong>ClientWorks v{resource.data.client.version} ↔ Wealthbox v{resource.data.contact?.version}</strong><p>Address and primary email only. One origin event, one propagation, and visible version conflicts.</p></div></div>{unresolved.map(conflict => <div className="notice warning" key={conflict.conflict_id}><InfoIcon/><div><strong>Contact update needs review</strong><p>{conflict.reason}</p><small>{conflict.field}: {conflict.proposed_value}</small><p>Review the fresh versions above and approve the intended value to resolve.</p></div></div>)}<form className="form-stack" onSubmit={event => { event.preventDefault(); synchronize() }}><div className="form-grid"><label>Update originates in<select value={origin} onChange={event => setOrigin(event.target.value)}><option value="clientworks">ClientWorks</option><option value="wealthbox">Wealthbox</option></select></label><label>Supported field<select value={field} onChange={event => setField(event.target.value)}><option value="address">Mailing address</option><option value="primary_email">Primary email</option></select></label></div><label>Client-confirmed contact value<input required minLength={5} type={field === 'primary_email' ? 'email' : 'text'} value={value} onChange={event => setValue(event.target.value)} placeholder={field === 'address' ? 'Complete client-confirmed address' : 'name@example.test'}/></label><label>Instruction source / confirmation record<input required minLength={8} value={instruction} onChange={event => setInstruction(event.target.value)} placeholder="Describe the synthetic client confirmation"/></label><label className="checkbox-row"><input type="checkbox" checked={approved} onChange={event => setApproved(event.target.checked)}/><span>I reviewed and approve this client-confirmed contact update.</span></label><div className="button-row"><Button className="primary" type="submit" disabled={action.busy || !approved}><RefreshCw size={15}/>Synchronize approved contact field</Button><Button className="quiet" type="button" disabled={action.busy || !approved || value.length < 5 || instruction.length < 8} onClick={() => synchronize(true)}>Demonstrate version conflict</Button></div></form><div className="sync-events">{resource.data.events.map(event => <div key={event.event_id}><CheckCircle2 size={15}/><span>{event.origin} → {event.field} · {event.propagations} propagation · {date(event.timestamp)}</span></div>)}</div><div className="notice info"><FileText size={17}/><span>Contact sync is separate from the account servicing request and its institution receipt.</span></div></>}</Panel>
}

function InfoIcon() { return <FileText size={18}/> }
